insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Angelica','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Savoy cabbage','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Silver linden','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Kiwi','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Allium (Onion)','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Garden onion','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Leek','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Garlic','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chives','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Lemon verbena','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cashew nut','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pineapple','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Dill','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Custard apple','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Wild celery','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Peanut','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Burdock','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Horseradish','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Tarragon','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Mugwort','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Asparagus','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Oat','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Star fruit','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Brazil nut','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Common beet','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Borage','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chinese mustard','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Swede','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Rape','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Common cabbage','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cauliflower','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Brussel sprouts','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Kohlrabi','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Broccoli','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chinese cabbage','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Turnip','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pigeon pea','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Tea','Teas');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Capers','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pepper (C. annuum)','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Papaya','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Safflower','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Caraway','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pecan nut','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chestnut','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Roman camomile','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chickpea','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Endive','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chicory','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chinese cinnamon','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Ceylon cinnamon','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Watermelon','Gourds');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Lime','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Lemon','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pummelo','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Mandarin orange (Clementine,Tangerine)','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sweet orange','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Coffee','Coffee and coffee products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Arabica coffee','Coffee and coffee products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Robusta coffee','Coffee and coffee products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Coriander','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Common hazelnut','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Saffron','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Muskmelon','Gourds');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cucumber','Gourds');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cucurbita (Gourd)','Gourds');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cumin','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Turmeric','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Quince','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Lemon grass','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Globe artichoke','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Wild carrot','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Japanese persimmon','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cardamom','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Black crowberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Loquat','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Rocket salad (ssp.)','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Wax apple','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Common buckwheat','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Tartary buckwheat','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Fig','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Fennel','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Strawberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Black huckleberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Soy bean','Soy');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sunflower','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sea-buckthornberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Barley','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Hyssop','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Star anise','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Swamp cabbage','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sweet potato','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Black walnut','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Common walnut','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Lettuce','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Grass pea','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sweet bay','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Lentils','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Garden cress','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Lovage','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Flaxseed','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Mexican oregano','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Lichee','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Lupine','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Apple','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Mango','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('German camomile','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Lemon balm','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Mentha (Mint)','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Orange mint','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cornmint','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Spearmint','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Peppermint','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Medlar','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Bitter gourd','Gourds');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Mulberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Black mulberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Nutmeg','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sweet basil','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Evening primrose','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Olive','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sweet marjoram','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pot marjoram','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Common oregano','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Rice','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Millet','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Poppy','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Passion fruit','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Parsnip','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Avocado','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Parsley','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Scarlet bean','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Lima bean','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Common bean','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Date','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Black chokeberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Anise','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pine nut','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pepper (Spice)','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pistachio','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Common pea','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Purslane','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Prunus (Cherry, Plum)','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Apricot','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sweet cherry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sour cherry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('European plum','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Almond','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Peach','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Guava','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pomegranate','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pear','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Radish','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Garden rhubarb','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Blackcurrant','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Redcurrant','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Gooseberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Watercress','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Rosemary','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Rubus (Blackberry, Raspberry)','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cloudberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Red raspberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Black raspberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sorrel','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Common sage','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Black elderberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Summer savory','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Winter savory','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Rye','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sesame','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Garden tomato','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cherry tomato','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Garden tomato (var.)','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Eggplant','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Potato','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Rowanberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sorghum','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Spinach','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cloves','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Tamarind','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Dandelion','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cocoa bean','Cocoa and cocoa products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Common thyme','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Linden','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Small-leaf linden','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Fenugreek','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Common wheat','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Vaccinium (Blueberry, Cranberry, Huckleberry)','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Lowbush blueberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sparkleberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Highbush blueberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('American cranberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Bilberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Lingonberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Vanilla','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Common verbena','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Broad bean','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Adzuki bean','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Gram bean','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Mung bean','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Climbing bean','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cowpea','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Muscadine grape','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Common grape','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Corn','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Ginger','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Arctic blackberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Banana','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Bayberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Elliott''s blueberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Canada blueberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Bog bilberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Buffalo currant','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Celeriac','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Celery stalks','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chinese chives','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('European cranberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Deerberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Ginseng','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cascade huckleberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Oval-leaf huckleberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Evergreen huckleberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Red huckleberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Longan','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Macadamia nut (M. tetraphylla)','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Garden onion (var.)','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Summer grape','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Fox grape','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Nectarine','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Peach (var.)','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pepper (C. baccatum)','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pepper (C. chinense)','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pepper (Capsicum)','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Rambutan','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Red rice','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Annual wild rice','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Swiss chard','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Lemon thyme','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Tronchuda cabbage','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Japanese walnut','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Welsh onion','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Hard wheat','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Shallot','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Rocket salad','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Carrot','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Triticale','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Black cabbage','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Half-highbush blueberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Celery leaves','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chicory leaves','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Komatsuna','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pak choy','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Napa cabbage','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chicory roots','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Grapefruit/Pummelo hybrid','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Grapefruit','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Jostaberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Kai-lan','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Italian oregano','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Oxheart cabbage','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Daikon radish','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Black radish','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Radish (var.)','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Red beetroot','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sweet rowanberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pineappple sage','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Skunk currant','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Beer','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Other bread','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Breakfast cereal','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Other soy product','Soy');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Other cereal product','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pasta','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Biscuit','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sourdough','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Spirit','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Fortified wine','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Other alcoholic beverage','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Abalone','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Abiyuch','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Acerola','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Acorn','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Winter squash','Gourds');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Agar','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Red king crab','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Alfalfa','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Allspice','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Amaranth','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Arrowhead','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Arrowroot','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Asian pear','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Atlantic herring','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Atlantic mackerel','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Painted comber','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Atlantic pollock','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Atlantic wolffish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Bamboo shoots','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Striped bass','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Beaver','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Beech nut','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Beluga whale','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Bison','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Black bear','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Alaska blackfish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Blue crab','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Blue mussel','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Northern bluefin tuna','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Bluefish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Wild boar','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Bowhead whale','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Breadfruit','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Breadnut tree seed','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Rapini','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Brown bear','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Buffalo','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Burbot','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Giant butterbur','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('American butterfish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Butternut','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Butternut squash','Gourds');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Calabash','Gourds');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cardoon','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Caribou','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Natal plum','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Carob','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Common carp','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cassava','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Channel catfish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chayote','Gourds');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cherimoya','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chervil','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chia','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chicken (Cock, Hen, Rooster)','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chinese broccoli','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chinese chestnut','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chinese water chestnut','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Garland chrysanthemum','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cisco','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Nuttall cockle','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Coconut','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pacific cod','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Atlantic cod','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Common octopus','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Corn salad','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cottonseed','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Catjang pea','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Malus (Crab apple)','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Squashberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Atlantic croaker','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cusk','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cuttlefish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Mule deer','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Devilfish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Dock','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Dolphin fish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Freshwater drum','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Mallard duck','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Dungeness crab','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Durian','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Eastern oyster','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Freshwater eel','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Elderberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Elk','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Emu','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Oregon yampah','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('European anchovy','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('European chestnut','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Turbot','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Fireweed','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Florida pompano','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Ginkgo nuts','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Greylag goose','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Grape','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Greenland halibut/turbot','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Groundcherry','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Grouper','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Guinea hen','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Haddock','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Hippoglossus (Common halibut)','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Hazelnut','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Hickory nut','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Horse','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Horseradish tree','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Alaska blueberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Hyacinth bean','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Irish moss','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pacific jack mackerel','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Jackfruit','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Japanese chestnut','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Java plum','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Jerusalem artichoke','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Jujube','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Jute','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Kale','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Kelp','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('King mackerel','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Kumquat','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Lambsquarters','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Leather chiton','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Wild leek','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Common ling','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Lingcod','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('American lobster','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Loganberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Lotus','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sacred lotus','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('White lupine','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Malabar spinach','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Mammee apple','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Purple mangosteen','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Alpine sweetvetch','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Milkfish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Monkfish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Moose','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Moth bean','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Mountain yam','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Striped mullet','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Muskrat','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('White mustard','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Mustard spinach','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('New Zealand spinach','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Nopal','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Ocean pout','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('North Pacific giant octopus','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Ohelo berry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Okra','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Tunicate','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Opossum','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Ostrich','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Spotted seal','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pacific herring','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pacific oyster','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pacific rockfish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Velvet duck','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pepper (C. frutescens)','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Common persimmon','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pheasant','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Northern pike','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pili nut','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Colorado pinyon','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pitanga','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Plains prickly pear','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('French plantain','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('American pokeweed','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Polar bear','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Opium poppy','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Prairie turnip','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Prickly pear','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Quinoa','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('European rabbit','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Raccoon','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Rainbow smelt','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Rainbow trout','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Malabar plum','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Rose hip','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Roselle','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Orange roughy','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sablefish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pink salmon','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chum salmon','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Coho salmon','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sockeye salmon','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chinook salmon','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Atlantic salmon','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Salmonberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Common salsify','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sapodilla','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Mamey sapote','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Spanish mackerel','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pacific sardine','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Scallop','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Scup','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sea cucumber','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Steller sea lion','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Bearded seal','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Ringed seal','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Seatrout','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sesbania flower','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('American shad','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Shark','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sheefish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sheep (Mutton, Lamb)','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sheepshead','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Hedge mustard','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Skipjack tuna','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Snapper','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Soursop','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Spelt','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Spirulina','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Squab','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Squirrel','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Strawberry guava','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Greater sturgeon','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('White sucker','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sugar apple','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pumpkinseed sunfish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Swordfish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Taro','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Teff','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Tilefish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Mexican groundcherry','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Towel gourd','Gourds');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Salmonidae (Salmon, Trout)','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Turkey','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cattle (Beef, Veal)','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Walleye','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Alaska pollock','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Wasabi','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Wax gourd','Gourds');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Whelk','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Coalfish pollock','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Broad whitefish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Whitefish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Whiting','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Wild rice','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Tea leaf willow','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Winged bean','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Yam','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Jicama','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Yautia','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Yellowfin tuna','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Yellowtail amberjack','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pollock','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Albacore tuna','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Gadus (Common cod)','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Atlantic halibut','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pacific halibut','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pacific salmon','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Smelt','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Clupeinae (Herring, Sardine, Sprat)','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Spiny lobster','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Snow crab','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Black-eyed pea','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Deer','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Macadamia nut','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Percoidei (Bass and others)','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Perciformes (Perch-like fishes)','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Arctic ground squirrel','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Rabbit','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Domestic goat','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Beefalo','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Antelope','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Bivalvia (Clam, Mussel, Oyster)','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Squid','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Shrimp','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Crayfish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Flatfish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Domestic pig (Piglet, Pork)','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Walrus','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Alaska wild rhubarb','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Oriental wheat','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Yardlong bean','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Great horned owl','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Quail','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Boysenberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Persian lime','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Feijoa','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Rowal','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Jew''s ear','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Common mushroom','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Shiitake','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Purple laver','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Wakame','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Enokitake','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Epazote','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Oyster mushroom','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cloud ear fungus','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Maitake','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Ostrich fern','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Spot croaker','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sourdock','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Tinda','Gourds');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Atlantic menhaden','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Wheat','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Common chokecherry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Agave','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Narrowleaf cattail','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Jellyfish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Anchovy','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Blue whiting','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Carp bream','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chanterelle','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sturgeon','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Charr','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cinnamon','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Crab','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Common dab','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Spiny dogfish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Anatidae (Duck, Goose, Swan)','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Anguilliformes (Eel)','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('True frog','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Garfish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Gadiformes (Cod, Hake)','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Mountain hare','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Lake trout','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Lemon sole','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Clawed lobster','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Lumpsucker','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Scombridae (Bonito, Mackerel, Tuna)','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Marine mussel','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Norway haddock','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Norway lobster','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Norway pout','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Oil palm','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('True oyster','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sago palm','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Persimmon','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pikeperch','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pleuronectidae (Dab, Halibut, Plaice)','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Rock ptarmigan','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pacific ocean perch','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Black salsify','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('True seal','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Red algae','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Kombu','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Snail','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('True sole','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Catfish','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Thistle','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Thunnus (Common tuna)','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Walnut','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cetacea (Dolphin, Porpoise, Whale)','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Columbidae (Dove, Pigeon)','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Conch','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Grape wine','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Berry wine','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Other wine','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Apple cider','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Liquor','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cheese','Milk and milk products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Milk (Cow)','Milk and milk products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Eggs','Eggs');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Yogurt','Milk and milk products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Bean','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Vodka','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Whisky','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Ice cream','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Gin','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Honey','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Liquorice','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Vinegar','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Rum','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Port wine','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Vermouth','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sherry','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Madeira wine','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Nougat','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Toffee','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cake','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pizza','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Ymer','Milk and milk products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Other snack food','Snack foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Crisp bread','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pastry','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Dragée','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chewing gum','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Marzipan','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Salad dressing','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sauce','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Salt','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Butter','Milk and milk products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Butter substitute','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cream','Milk and milk products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sugar','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sausage','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Meatball','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Mustard','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pate','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sugar substitute','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Meat bouillon','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Other meat product','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Whey','Milk and milk products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Casein','Milk and milk products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Fruit preserve','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Leavening agent','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Marshmallow','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Gelatin','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Water','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Other fish product','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Milk (Human)','Milk and milk products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Other beverage','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Baby food','Baby foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Dumpling','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Soup','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Other vegetable product','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Unclassified food or beverage','Unclassified');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Syrup','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Tallow','Fats and oils');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Remoulade','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chocolate spread','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Fruit gum','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Curry powder','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Other candy','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Meringue','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Lard','Fats and oils');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Other animal fat','Fats and oils');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Other cocoa product','Cocoa and cocoa products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cocoa butter','Cocoa and cocoa products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cocoa powder','Cocoa and cocoa products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cocoa liquor','Cocoa and cocoa products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chocolate','Cocoa and cocoa products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Hot chocolate','Cocoa and cocoa products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Dried milk','Milk and milk products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Milk (Other mammals)','Milk and milk products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Kefir','Milk and milk products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Buttermilk','Milk and milk products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Other fermented milk','Milk and milk products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Soy sauce','Soy');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Miso','Soy');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Tofu','Soy');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Zwieback','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Roe','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cichlidae (Tilapia)','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Icing','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Snack bar','Snack foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Green turtle','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Energy drink','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Burrito','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Hamburger','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Baked beans','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chili','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Taco','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Tortilla','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Nachos','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Processed cheese','Milk and milk products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Salad','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cream substitute','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Dulce de leche','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Topping','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sweet custard','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Egg roll','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Heart of palm','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Popcorn','Snack foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Potato chip','Snack foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Tortilla chip','Snack foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Corn chip','Snack foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Hibiscus tea','Teas');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Stew','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Gelatin dessert','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Junket','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Falafel','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Frybread','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Other frozen dessert','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Lasagna','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Morchella (Morel)','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pancake','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pectin','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pudding','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Waffle','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Soy milk','Soy');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Meatloaf','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sake','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cocktail','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Couscous','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Bulgur','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Coffee substitute','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Coffee mocha','Coffee and coffee products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chimichanga','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Semolina','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Tapioca pearl','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Tostada','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Quesadilla','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Baked potato','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Hot dog','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Spread','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Enchilada','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Egg substitute','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Nutritional drink','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Other sandwich','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Ketchup','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Breakfast sandwich','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Adobo','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Macaroni and cheese','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Butterfat','Milk and milk products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Horned melon','Gourds');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Hushpuppy','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Fruit juice','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Relish','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Other fruit product','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Fruit salad','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Soy yogurt','Soy');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Vegetarian food','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Veggie burger','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cold cut','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Mixed nuts','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Canola','Herbs and spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Babassu palm','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cupuaçu','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Shea tree','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Oil-seed Camellia','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Ucuhuba','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Phyllo dough','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cooking oil','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pie crust','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pie filling','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pie','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Shortening','Fats and oils');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Soy cream','Soy');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Ice cream cone','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Molasses','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cracker','Snack foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Nance','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Naranjilla','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Natto','Soy');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Ravioli','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Scrapple','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Other pasta dish','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Succotash','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Tamale','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Rice cake','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Tree fern','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Evaporated milk','Milk and milk products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Flour','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Akutaq','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Dough','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pita bread','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Focaccia','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Bagel','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Other bread product','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Piki bread','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('French toast','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Wheat bread','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Rye bread','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Oat bread','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Potato bread','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cornbread','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Corn grits','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Multigrain bread','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Rice bread','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pan dulce','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Raisin bread','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Wonton wrapper','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Trail mix','Snack foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Greenthread tea','Teas');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Fruit-flavor drink','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Vegetable juice','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Horchata','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Soft drink','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Frozen yogurt','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Milkshake','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chocolate mousse','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Dripping','Fats and oils');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pupusa','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Empanada','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Arepa','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Ascidians','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Gefilte fish','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Yellow pond-lily','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Fish burger','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Other dish','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pot pie','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Stuffing','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Edible shell','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Fudge','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Candy bar','Confectioneries');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Condensed milk','Milk and milk products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Margarine','Fats and oils');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Margarine-like spread','Fats and oils');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Hummus','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Potato puffs','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Potato gratin','Dishes');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Milk substitute','Baking goods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pepper (C. pubescens)','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Soft-necked garlic','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cabbage','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Chinese bayberry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Mushrooms','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Alcoholic beverages','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Onion-family vegetables','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pomes','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Brassicas','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cereals and cereal products','Cereals and cereal products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Citrus','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Cocoa and cocoa products','Cocoa and cocoa products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Coffee and coffee products','Coffee and coffee products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Crustaceans','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Milk and milk products','Milk and milk products');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Fats and oils','Fats and oils');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Fishes','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Herbs and Spices','Herbs and Spices');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Pulses','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Animal foods','Animal foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Mollusks','Aquatic foods');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Nuts','Nuts');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Beverages','Beverages');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Fruits','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Green vegetables','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Root vegetables','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Sunburst squash (pattypan squash)','Gourds');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Green zucchini','Gourds');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Yellow zucchini','Gourds');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Green bell pepper','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Yellow bell pepper','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Orange bell pepper','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Red bell pepper','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Italian sweet red pepper','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Yellow wax bean','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Green bean','Pulses');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Saskatoon berry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Nanking cherry','Fruits');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Japanese pumpkin','Gourds');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('White cabbage','Vegetables');
insert into [MenuGer].[dbo].[ingredients] ([name],[ingredient_group]) values('Romaine lettuce','Vegetables');
